# include: "rules/scran-01-preprocessing.smk"
include: "rules/scran-02-batch.smk"


# inclue 会有命名冲突module没有命名冲突
# 设置默认目标
# 这确保了在运行 `snakemake` 时，如果没有指定目标，
# 它将尝试构建指定的默认目标，从而触发必要的规则以生成所需的输出。
rule run:
    input:
        rules.all.input,
