include: "rules/module1.smk"
include: "rules/module2.smk"

include: "rules/module3-example-py.smk"

# 设置默认目标
# 这确保了在运行 `snakemake` 时，如果没有指定目标，
# 它将尝试构建指定的默认目标，从而触发必要的规则以生成所需的输出。
rule all:
    input:
        "results/outputs.txt",
