include: "rules/example-01-base.smk"
include: "rules/example-02-notebook.smk"
include: "rules/example-03-script.smk"


# 设置默认目标
# 这确保了在运行 `snakemake` 时，如果没有指定目标，
# 它将尝试构建指定的默认目标，从而触发必要的规则以生成所需的输出。
rule all:
    input:
        "results/outputs.txt",
