input_file_list:
  # 批量分析使用文件基本名作为样本名
  - "data/adata_raw.h5ad" # 批量模式初始输入文件

samples:
  adata_raw:
    control_label: "CNL"
    treatment_label: "CCL"
  sample2:
    control_label: "CNL_2"
    treatment_label: "TMT_2"
  sample3:
    control_label: "CNL_3"
    treatment_label: "TMT_3"

# 基础目录配置
input_dir: "data"
output_dir: "results"
figure_dir: "figures"
table_dir: "table"
condition_column: "group" # 分组信息列名
sample_group_column: "patients_organ" # 样本信息列名
ctrol_column: "CNL" # 对照组列名
treat_column: "CCL" # 处理组列名

# 环境配置
env:
  conda: "lang"
  pertpy: "../envs/pertpy_env.yaml"

# 质量控制参数
quality_control:
  input_file: "adata_raw.h5ad" # 初始输入文件

  mad_general: 5 # 一般特征的MAD阈值，双端
  mad_mt: 3 # 线粒体基因的MAD阈值，单端
  mt_threshold: 20 # 线粒体基因比例阈值(%)

# 双细胞去除参数
doublet_removal:
  random_state: 123 # 随机数种子,保证结果可重复
  batch_key: "batch" # 批次信息列名

# 标准化参数
normalization:

# 高变基因识别参数
find_hvg:
  n_top_genes: 2000 # 选择的高变基因数量
  batch_key: "batch" # 批次信息列名

batch_removal:
  batch_key: "batch"
  covariate_keys:
    - "group" # yaml的数组语法
  n_top_pcs: 10 # just for harmony
  n_neighbors: 15
  methods:
    # - scvi
    - harmony

cluster:
  # 聚类参数
  leiden:
    n_neighbors: 15
    resolutions: [0.25, 0.5, 1, 2] # 每多一个耗时多一倍

  # 基因预览
  species: "human" # 可选: "human", "mouse", "rat"

  # 可视化参数
  plot_params:
    vmax: "p90"
    vmin: "p05"
    cmap: "bwr"
    ncols: 3
    wspace: 0.2
    legend_loc: "on data"

cell_annotation:
  anno_type:
    - celltypist
  plot_params:
    # vmax: "p90"
    # vmin: "p05"
    # cmap: "bwr"
    ncols: 2
    wspace: 0.5
    # legend_loc: "on data"

find_markers:
  test_methods: t-test
  group_key: "leiden_0_25"
  plot_params:
    # vmax: "p90"
    # vmin: "p05"
    # cmap: "bwr"
    ncols: 2
    wspace: 0.2
    # legend_loc: "on data"
